project:
  type: website
  output-dir: docs # Github Pages requires this
  preview:
    host: 0.0.0.0
    port: 8080
  post-render:
    - post-render.sh
  render:
    - "*.qmd"
    - "!*pyscript.qmd"

website:
  title: "Trent Nelson"
  favicon: "favicon.ico"
  site-url: "https://trent.me"
  repo-url: "https://github.com/tpn/website"
  issue-url: "https://github.com/tpn/website/issues/new/choose"
  #google-analytics: "UA-24686252-1"
  google-analytics:
    tracking-id: "G-8RPR4XKPEW"
    anonymize-ip: false
    version: 4
  repo-actions: [edit, issue]
  twitter-card: true
  open-graph: true
  page-navigation: true
  bread-crumbs: true
  reader-mode: true
  draft-mode: visible
  search:
    show-item-context: true
    type: overlay
  comments:
    giscus:
      repo: tpn/website
      category: Announcements
      mapping: pathname
      theme: dark
  navbar:
    left:
      - text: Articles
        href: articles/index.qmd
      - text: Projects & Repos
        href: projects/index.qmd
      - text: Tools
        href: tools/index.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/trentnelson
        text: Twitter
      - icon: github
        href: https://github.com/tpn
        text: GitHub
      - icon: linkedin
        href: https://www.linkedin.com/in/trent-p-nelson
        text: LinkedIn

format:
  html:
    #link-external-icon: true
    syntax-definitions:
      - asm.xml
      - c.xml
    highlight-style: tpn.theme
    #fig-cap-location: margin
    #reference-location: margin
    #citation-location: margin
    theme:
      #dark: [journal, theme-dark.scss]
      #light: journal
      dark: [darkly, theme.scss, theme-dark.scss]
      light: [flatly, theme.scss, theme-light.scss]
    css: styles.css
    toc: true
    toc-depth: 5
    #toc-expand: true
    toc-location: right-body
    toc-title: Contents
    grid:
      margin-width: 380px

#filters:
  #- auto-dark

