project:
  type: website
  output-dir: _site

website:
  title: "Trent Nelson"
  image: "bluebg.jpg"
  favicon: "favicon.ico"
  site-url: "https://trent.me"
  repo-url: "https://github.com/tpn/website"
  issue-url: "https://github.com/tpn/website/issues/new/choose"
  repo-actions: [edit, issue]
  page-navigation: true
  bread-crumbs: true
  search:
    show-item-context: true
    type: overlay
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



